<?php

declare(strict_types=1);

namespace SignalWire\REST;

use SignalWire\REST\Namespaces\Generated\ResourceTree;

/**
 * Top-level SignalWire REST client.
 *
 * Provides lazy access to every API namespace (fabric, calling,
 * phone_numbers, datasphere, video, etc.).  Credentials can be
 * supplied explicitly or pulled from environment variables.
 *
 * The flat resource + namespace-container accessors (fabric, video, calling,
 * phoneNumbers, registry, logs, project, datasphere, addresses, queues, ...)
 * are composed from the generated ``ResourceTree`` trait — the client object
 * tree is spec-derived, regenerated by
 * scripts/generate_rest.py, mirroring the Python reference's
 * ``_client_tree_generated`` assembly. The hand client keeps only what is NOT
 * spec-derivable: credentials/auth and HTTP-layer construction.
 */
class RestClient
{
    use ResourceTree;

    private string $projectId;
    private string $token;
    private string $space;
    /** @var non-empty-string */
    private string $baseUrl;
    private HttpClient $http;

    /**
     * @param string $project Project ID (falls back to SIGNALWIRE_PROJECT_ID env var).
     * @param string $token   API token  (falls back to SIGNALWIRE_API_TOKEN env var).
     * @param string $host    Space host or full base URL.
     *                        - "mycompany.signalwire.com" → https://mycompany.signalwire.com
     *                        - "https://example.com:8080" → used verbatim
     *                        - "http://127.0.0.1:8080"   → used verbatim (test fixtures)
     *                        Falls back to SIGNALWIRE_SPACE env var.
     * @param RequestOptions|null $requestOptions Client-default transport
     *        options (timeout / retries / retry policy / abort) applied to every
     *        request; each REST verb also accepts a per-request override that
     *        shallow-merges over this. Mirrors Python's
     *        ``RestClient(request_options=...)``. Ordered before ``$caBundle``
     *        to match the reference's ``(project, token, host, request_options)``
     *        positional shape; ``$caBundle`` is the php-only trailing extra.
     *
     * Parameter names mirror the Python reference's
     * ``RestClient(project=, token=, host=, request_options=)`` so named-argument
     * call sites are cross-port identical; the constructor also accepts these
     * positionally.
     */
    public function __construct(
        string $project = '',
        string $token = '',
        string $host = '',
        ?RequestOptions $requestOptions = null,
        ?string $caBundle = null
    ) {
        $this->projectId = $project !== '' ? $project : (string) getenv('SIGNALWIRE_PROJECT_ID');
        $this->token     = $token   !== '' ? $token : (string) getenv('SIGNALWIRE_API_TOKEN');
        $this->space     = $host    !== '' ? $host : (string) getenv('SIGNALWIRE_SPACE');

        if ($this->projectId === '') {
            throw new \InvalidArgumentException(
                'projectId is required (pass explicitly or set SIGNALWIRE_PROJECT_ID)'
            );
        }
        if ($this->token === '') {
            throw new \InvalidArgumentException(
                'token is required (pass explicitly or set SIGNALWIRE_API_TOKEN)'
            );
        }
        if ($this->space === '') {
            throw new \InvalidArgumentException(
                'space is required (pass explicitly or set SIGNALWIRE_SPACE)'
            );
        }

        // Accept a bare host ("space.signalwire.com") or a fully-qualified
        // URL. The latter is used by tests and audit harnesses to point
        // the client at a loopback fixture without forcing https://.
        $baseUrl = preg_match('#^https?://#i', $this->space)
            ? rtrim($this->space, '/')
            : 'https://' . $this->space;
        // Genuine invariant: $space is non-empty (thrown above), so the
        // https:// branch is non-empty by construction, and the rtrim branch
        // strips only trailing '/' from a URL that already begins with a
        // scheme (so it cannot reduce to ''). PHPStan can't infer this through
        // rtrim/preg_match, so establish the true type at the source.
        assert($baseUrl !== '');
        $this->baseUrl = $baseUrl;
        $this->http = new HttpClient($this->projectId, $this->token, $this->baseUrl, $requestOptions, $caBundle);
    }

    /**
     * The HttpClient the generated ResourceTree hangs its resources off.
     * Satisfies the trait's abstract hook so construction stays
     * ``Resource($http)`` throughout the generated tree.
     */
    protected function generatedHttpClient(): HttpClient
    {
        return $this->http;
    }

    // -----------------------------------------------------------------
    // Getters
    // -----------------------------------------------------------------

    public function getProjectId(): string
    {
        return $this->projectId;
    }

    public function getToken(): string
    {
        return $this->token;
    }

    public function getSpace(): string
    {
        return $this->space;
    }

    public function getBaseUrl(): string
    {
        return $this->baseUrl;
    }

    public function getHttp(): HttpClient
    {
        return $this->http;
    }
}
