<?php

declare(strict_types=1);

namespace SignalWire\REST;

use SignalWire\REST\Namespaces\Generated\ResourceTree;

/**
 * Top-level SignalWire REST client.
 *
 * Provides lazy access to every API namespace (fabric, calling,
 * phone_numbers, datasphere, video, etc.).  Credentials can be
 * supplied explicitly or pulled from environment variables.
 *
 * The flat resource + namespace-container accessors (fabric, video, calling,
 * phoneNumbers, registry, logs, project, datasphere, addresses, queues, ...)
 * are composed from the generated ``ResourceTree`` trait — the client object
 * tree is spec-derived, regenerated by
 * scripts/generate_rest.py, mirroring the Python reference's
 * ``_client_tree_generated`` assembly. The hand client keeps only what is NOT
 * spec-derivable: credentials/auth and HTTP-layer construction.
 *
 * The Space Administration API (``$client->space()``) authenticates with a
 * user's Personal Access Token instead of a project token:
 *
 *     $admin = new RestClient(host: 'your-space.signalwire.com', personalAccessToken: 'pat_...');
 *     $admin->space()->members()->list();
 */
class RestClient
{
    use ResourceTree;

    private string $projectId;
    private string $token;
    private string $host;
    /** @var non-empty-string */
    private string $baseUrl;
    private HttpClient $http;
    private HttpClient $patHttp;

    /**
     * @param string $project Project ID (falls back to SIGNALWIRE_PROJECT_ID env var).
     * @param string $token   API token  (falls back to SIGNALWIRE_API_TOKEN env var).
     * @param string $host    Space host or full base URL.
     *                        - "mycompany.signalwire.com" → https://mycompany.signalwire.com
     *                        - "https://example.com:8080" → used verbatim
     *                        - "http://127.0.0.1:8080"   → used verbatim (test fixtures)
     *                        Falls back to SIGNALWIRE_SPACE env var.
     * @param RequestOptions|null $requestOptions Client-default transport
     *        options (timeout / retries / retry policy / abort) applied to every
     *        request; each REST verb also accepts a per-request override that
     *        shallow-merges over this. Mirrors Python's
     *        ``RestClient(request_options=...)``. Ordered before ``$caBundle``
     *        to match the reference's ``(project, token, host, request_options)``
     *        positional shape; ``$caBundle`` is the php-only trailing extra.
     * @param string|null $personalAccessToken A user's Personal Access Token
     *        (``pat_...``; falls back to SIGNALWIRE_PERSONAL_ACCESS_TOKEN). It
     *        authenticates ``space()`` — the Space Administration API, which the
     *        server serves only to a Personal Access Token (HTTP Basic with an
     *        empty username). Either credential, or both, may be given; a request
     *        on a resource whose credential is missing throws
     *        ``\InvalidArgumentException`` before anything is sent.
     * @param string|null $caBundle Optional CA bundle (PEM) for HTTPS peer
     *        verification (php-only trailing extra).
     *
     * Parameter names mirror the Python reference's
     * ``RestClient(project=, token=, host=, request_options=, personal_access_token=)``
     * so named-argument call sites are cross-port identical; the constructor
     * also accepts these positionally.
     *
     * @throws \InvalidArgumentException if the host is missing, or if neither a
     *         complete project + token pair nor a personal access token is given.
     */
    public function __construct(
        string $project = '',
        string $token = '',
        string $host = '',
        ?RequestOptions $requestOptions = null,
        ?string $personalAccessToken = null,
        ?string $caBundle = null
    ) {
        $this->projectId = $project !== '' ? $project : (string) getenv('SIGNALWIRE_PROJECT_ID');
        $this->token     = $token   !== '' ? $token : (string) getenv('SIGNALWIRE_API_TOKEN');
        $this->host      = $host    !== '' ? $host : (string) getenv('SIGNALWIRE_SPACE');
        $pat = $personalAccessToken !== null && $personalAccessToken !== ''
            ? $personalAccessToken
            : (string) getenv('SIGNALWIRE_PERSONAL_ACCESS_TOKEN');
        $hasProject = $this->projectId !== '' && $this->token !== '';

        if (!$hasProject && $pat === '') {
            throw new \InvalidArgumentException(
                'projectId and token are required (pass explicitly or set '
                . 'SIGNALWIRE_PROJECT_ID / SIGNALWIRE_API_TOKEN); for space() only, a '
                . 'personalAccessToken (or SIGNALWIRE_PERSONAL_ACCESS_TOKEN) may be given instead'
            );
        }
        if ($this->host === '') {
            throw new \InvalidArgumentException(
                'space is required (pass explicitly or set SIGNALWIRE_SPACE)'
            );
        }

        // Accept a bare host ("space.signalwire.com") or a fully-qualified
        // URL. The latter is used by tests and audit harnesses to point
        // the client at a loopback fixture without forcing https://.
        //
        // A BARE loopback host (127.0.0.1[:port] / localhost[:port]) is a local
        // mock/dev server that speaks plain HTTP, so pick http:// for it — this
        // lets a shipped example/doc run verbatim against the local mock via
        // SIGNALWIRE_SPACE=127.0.0.1:<port> without a code change or an explicit
        // scheme. Mirrors the python reference `_is_loopback_host`
        // (signalwire/rest/_base.py). A real space (<name>.signalwire.com) is
        // never loopback, so production is unaffected. An explicit scheme in the
        // host string is always honored verbatim (the branch above).
        if (preg_match('#^https?://#i', $this->host)) {
            $baseUrl = rtrim($this->host, '/');
        } else {
            $scheme = self::isLoopbackHost($this->host) ? 'http' : 'https';
            $baseUrl = $scheme . '://' . $this->host;
        }
        // Genuine invariant: $space is non-empty (thrown above), so the
        // https:// branch is non-empty by construction, and the rtrim branch
        // strips only trailing '/' from a URL that already begins with a
        // scheme (so it cannot reduce to ''). PHPStan can't infer this through
        // rtrim/preg_match, so establish the true type at the source.
        assert($baseUrl !== '');
        $this->baseUrl = $baseUrl;
        $this->http = $hasProject
            ? new HttpClient($this->projectId, $this->token, $this->baseUrl, $requestOptions, $caBundle)
            : self::missingCredentialHttp(
                $this->baseUrl,
                'projectId and token are required for this resource '
                . '(SIGNALWIRE_PROJECT_ID / SIGNALWIRE_API_TOKEN); this client has only '
                . 'a personal access token, which authenticates space()'
            );
        // A Personal Access Token is HTTP Basic with an EMPTY username (the
        // server's Space API authenticator), so it rides the same HttpClient
        // with '' as the user part.
        $this->patHttp = $pat !== ''
            ? new HttpClient('', $pat, $this->baseUrl, $requestOptions, $caBundle)
            : self::missingCredentialHttp(
                $this->baseUrl,
                'personalAccessToken is required for space() '
                . '(SIGNALWIRE_PERSONAL_ACCESS_TOKEN)'
            );
    }

    /**
     * Stand-in HTTP client for a credential this RestClient was not given:
     * every request throws ``\InvalidArgumentException`` naming the missing
     * credential before anything is sent, so a PAT-only client fails loudly on
     * a project resource (and a project-only client on ``space()``) instead of
     * sending a request the server can only refuse. Mirrors the reference's
     * ``_MissingCredentialHttp``.
     *
     * @param non-empty-string $baseUrl
     */
    private static function missingCredentialHttp(string $baseUrl, string $message): HttpClient
    {
        return new MissingCredentialHttpClient($baseUrl, $message);
    }

    /**
     * True if ``$host`` (bare host or host:port) is a local loopback address —
     * a local mock/dev server that speaks plain HTTP. Used to pick http:// vs
     * https:// so a shipped example runs verbatim against the local mock. A real
     * SignalWire space (``<name>.signalwire.com``) is never loopback, so
     * production is unaffected. Mirrors python's ``_is_loopback_host``.
     */
    private static function isLoopbackHost(string $host): bool
    {
        $hostname = str_contains($host, ':') ? substr($host, 0, strrpos($host, ':') ?: 0) : $host;

        return in_array($hostname, ['127.0.0.1', 'localhost', '::1', '[::1]'], true);
    }

    /**
     * The HttpClient the generated ResourceTree hangs its resources off.
     * Satisfies the trait's abstract hook so construction stays
     * ``Resource($http)`` throughout the generated tree.
     */
    protected function generatedHttpClient(): HttpClient
    {
        return $this->http;
    }

    /**
     * The Personal-Access-Token HttpClient the generated ResourceTree wires the
     * PAT-secured namespaces (``space()``) to.
     */
    protected function generatedPatHttpClient(): HttpClient
    {
        return $this->patHttp;
    }

    // -----------------------------------------------------------------
    // Getters
    // -----------------------------------------------------------------

    /** The project ID. */
    public function getProjectId(): string
    {
        return $this->projectId;
    }

    /** The API token. */
    public function getToken(): string
    {
        return $this->token;
    }

    /** The SignalWire space (host). */
    public function getSpace(): string
    {
        return $this->host;
    }

    /** The base URL. */
    public function getBaseUrl(): string
    {
        return $this->baseUrl;
    }

    /** The underlying HTTP client. */
    public function getHttp(): HttpClient
    {
        return $this->http;
    }
}
