<?php

declare(strict_types=1);

namespace SignalWire\Tests;

use PHPUnit\Framework\TestCase;
use SignalWire\Logging\Logger;
use SignalWire\SWML\Schema;
use SignalWire\SWML\Service;
use SignalWire\Tests\Support\Shape;

class SWMLServiceTest extends TestCase
{
    protected function setUp(): void
    {
        Schema::reset();
        Logger::reset();
        putenv('SWML_BASIC_AUTH_USER');
        putenv('SWML_BASIC_AUTH_PASSWORD');
        putenv('SWML_PROXY_URL_BASE');
        putenv('PORT');
    }

    protected function tearDown(): void
    {
        Schema::reset();
        Logger::reset();
        putenv('SWML_BASIC_AUTH_USER');
        putenv('SWML_BASIC_AUTH_PASSWORD');
        putenv('SWML_PROXY_URL_BASE');
        putenv('PORT');
    }

    /**
     * @param array{
     *     name?: string,
     *     route?: string,
     *     host?: ?string,
     *     port?: ?int,
     *     basic_auth_user?: string,
     *     basic_auth_password?: string
     * } $opts
     */
    private function makeService(array $opts = []): Service
    {
        return new Service(
            name: $opts['name'] ?? 'test-service',
            route: $opts['route'] ?? '/',
            host: $opts['host'] ?? null,
            port: $opts['port'] ?? null,
            basicAuthUser: $opts['basic_auth_user'] ?? 'testuser',
            basicAuthPassword: $opts['basic_auth_password'] ?? 'testpass'
        );
    }

    /** @return array<string,string> */
    private function authHeader(string $user = 'testuser', string $pass = 'testpass'): array
    {
        return ['Authorization' => 'Basic ' . base64_encode("{$user}:{$pass}")];
    }

    // ------------------------------------------------------------------
    // Construction
    // ------------------------------------------------------------------

    public function testConstruction(): void
    {
        $svc = $this->makeService();
        $this->assertSame('test-service', $svc->getName());
        $this->assertSame('/', $svc->getRoute());
        $this->assertSame('0.0.0.0', $svc->getHost());
        $this->assertSame(3000, $svc->getPort());
    }

    public function testCustomRoute(): void
    {
        $svc = $this->makeService(['route' => '/myagent']);
        $this->assertSame('/myagent', $svc->getRoute());
    }

    public function testRouteTrailingSlashStripped(): void
    {
        $svc = $this->makeService(['route' => '/myagent/']);
        $this->assertSame('/myagent', $svc->getRoute());
    }

    public function testPortFromEnv(): void
    {
        putenv('PORT=8080');
        $svc = new Service(
            name: 'test',
            basicAuthUser: 'u',
            basicAuthPassword: 'p'
        );
        $this->assertSame(8080, $svc->getPort());
    }

    public function testPortExplicitOverridesEnv(): void
    {
        putenv('PORT=8080');
        $svc = $this->makeService(['port' => 9090]);
        $this->assertSame(9090, $svc->getPort());
    }

    // ------------------------------------------------------------------
    // Auth
    // ------------------------------------------------------------------

    public function testExplicitAuth(): void
    {
        $svc = $this->makeService([
            'basic_auth_user' => 'myuser',
            'basic_auth_password' => 'mypass',
        ]);
        $this->assertSame(['myuser', 'mypass'], $svc->getBasicAuthCredentials());
    }

    public function testEnvAuth(): void
    {
        putenv('SWML_BASIC_AUTH_USER=envuser');
        putenv('SWML_BASIC_AUTH_PASSWORD=envpass');
        $svc = new Service(name: 'test');
        $this->assertSame(['envuser', 'envpass'], $svc->getBasicAuthCredentials());
    }

    public function testAutoGeneratedAuth(): void
    {
        $svc = new Service(name: 'test');
        [$user, $pass] = $svc->getBasicAuthCredentials();
        $this->assertNotEmpty($user);
        $this->assertNotEmpty($pass);
        $this->assertGreaterThan(8, strlen($user));
        $this->assertGreaterThan(8, strlen($pass));
    }

    public function testAutoGeneratedAuthIsDifferentEachTime(): void
    {
        $svc1 = new Service(name: 'test1');
        $svc2 = new Service(name: 'test2');
        [$user1,] = $svc1->getBasicAuthCredentials();
        [$user2,] = $svc2->getBasicAuthCredentials();
        $this->assertNotSame($user1, $user2);
    }

    public function testGetFullUrl(): void
    {
        $svc = $this->makeService();
        $this->assertSame('http://0.0.0.0:3000/', $svc->getFullUrl());
    }

    public function testGetFullUrlWithAuth(): void
    {
        $svc = $this->makeService([
            'basic_auth_user' => 'u',
            'basic_auth_password' => 'p',
        ]);
        $this->assertSame('http://u:p@0.0.0.0:3000/', $svc->getFullUrl(true));
    }

    public function testGetFullUrlWithRoute(): void
    {
        $svc = $this->makeService(['route' => '/agent']);
        $this->assertSame('http://0.0.0.0:3000/agent', $svc->getFullUrl());
    }

    // ------------------------------------------------------------------
    // Verb auto-vivification (__call)
    // ------------------------------------------------------------------

    public function testAnswerVerb(): void
    {
        $svc = $this->makeService();
        $svc->answer(['max_duration' => 3600]); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)

        $verbs = $svc->getDocument()->getVerbs('main');
        $this->assertCount(1, $verbs);
        $this->assertSame(['answer' => ['max_duration' => 3600]], $verbs[0]);
    }

    public function testHangupVerbNoArgs(): void
    {
        $svc = $this->makeService();
        $svc->hangup(); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)

        $verbs = $svc->getDocument()->getVerbs('main');
        $this->assertCount(1, $verbs);
        // A no-arg verb is an empty OBJECT, so it renders as {"hangup":{}} on
        // the wire (SWML contract + python parity), NOT {"hangup":[]}.
        $this->assertEquals(['hangup' => new \stdClass()], $verbs[0]);
        $rendered = $svc->getDocument()->render();
        $this->assertStringContainsString('"hangup":{}', $rendered);
        $this->assertStringNotContainsString('"hangup":[]', $rendered);
    }

    public function testSleepVerbInteger(): void
    {
        $svc = $this->makeService();
        $svc->sleep(2000); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)

        $verbs = $svc->getDocument()->getVerbs('main');
        $this->assertSame(['sleep' => 2000], $verbs[0]);
    }

    public function testSleepVerbWithSection(): void
    {
        $svc = $this->makeService();
        $svc->getDocument()->addSection('custom');
        $svc->sleep('custom', 1000); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)

        $verbs = $svc->getDocument()->getVerbs('custom');
        $this->assertSame(['sleep' => 1000], $verbs[0]);
    }

    public function testVerbWithSection(): void
    {
        $svc = $this->makeService();
        $svc->getDocument()->addSection('custom');
        $svc->answer('custom', ['max_duration' => 7200]); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)

        $verbs = $svc->getDocument()->getVerbs('custom');
        $this->assertSame(['answer' => ['max_duration' => 7200]], $verbs[0]);
    }

    public function testVerbChaining(): void
    {
        $svc = $this->makeService();
        $result = $svc->answer(['max_duration' => 3600]); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)
        $this->assertSame($svc, $result);
    }

    public function testMultipleVerbs(): void
    {
        $svc = $this->makeService();
        $svc->answer(['max_duration' => 3600]) // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)
            ->sleep(1000)
            ->hangup();

        $verbs = $svc->getDocument()->getVerbs('main');
        $this->assertCount(3, $verbs);
    }

    public function testAllSchemaVerbsCallable(): void
    {
        $svc = $this->makeService();
        $schema = Schema::instance();
        $names = $schema->getVerbNames();

        foreach ($names as $verb) {
            if ($verb === 'sleep') {
                $svc->sleep(1000); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)
            } else {
                $svc->$verb([]);
            }
        }

        $verbs = $svc->getDocument()->getVerbs('main');
        $this->assertCount(count($names), $verbs);
    }

    public function testUnknownMethodThrows(): void
    {
        $svc = $this->makeService();
        $this->expectException(\BadMethodCallException::class);
        $svc->nonexistentVerb(); // @phpstan-ignore method.notFound (deliberately-undefined verb to exercise the BadMethodCallException path)
    }

    // ------------------------------------------------------------------
    // HTTP Handling: Health/Ready
    // ------------------------------------------------------------------

    public function testHealthEndpoint(): void
    {
        $svc = $this->makeService();
        [$status, $headers, $body] = $svc->handleRequest('GET', '/health');

        $this->assertSame(200, $status);
        $this->assertSame('application/json', $headers['Content-Type']);
        $decoded = json_decode($body, true);
        $this->assertSame('healthy', Shape::at($decoded, 'status'));
    }

    public function testReadyEndpoint(): void
    {
        $svc = $this->makeService();
        [$status, $headers, $body] = $svc->handleRequest('GET', '/ready');

        $this->assertSame(200, $status);
        $decoded = json_decode($body, true);
        $this->assertSame('ready', Shape::at($decoded, 'status'));
    }

    public function testHealthNoAuthRequired(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('GET', '/health');
        $this->assertSame(200, $status);
    }

    // ------------------------------------------------------------------
    // HTTP Handling: Auth
    // ------------------------------------------------------------------

    public function testRootWithoutAuthReturns401(): void
    {
        $svc = $this->makeService();
        [$status, $headers,] = $svc->handleRequest('GET', '/');

        $this->assertSame(401, $status);
        $this->assertArrayHasKey('WWW-Authenticate', $headers);
    }

    public function testRootWithCorrectAuth(): void
    {
        $svc = $this->makeService();
        [$status, $headers, $body] = $svc->handleRequest('GET', '/', $this->authHeader());

        $this->assertSame(200, $status);
        $decoded = json_decode($body, true);
        $this->assertSame('1.0.0', Shape::at($decoded, 'version'));
    }

    public function testWrongPasswordReturns401(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('GET', '/', $this->authHeader('testuser', 'wrongpass'));
        $this->assertSame(401, $status);
    }

    public function testWrongUserReturns401(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('GET', '/', $this->authHeader('wronguser', 'testpass'));
        $this->assertSame(401, $status);
    }

    public function testNoAuthHeaderReturns401(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('GET', '/');
        $this->assertSame(401, $status);
    }

    public function testBadAuthSchemeReturns401(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('GET', '/', ['Authorization' => 'Bearer token123']);
        $this->assertSame(401, $status);
    }

    // ------------------------------------------------------------------
    // HTTP Handling: Security Headers
    // ------------------------------------------------------------------

    public function testHandleRequestCoreReturnsBareHeaders(): void
    {
        // Python parity (SWMLService._handle_request_core): the framework-free
        // dispatch core returns bare (200, {}, swml) / (401, {WWW-Authenticate},
        // json) triples. Security headers are applied by the SERVING layer
        // (WebService / AgentServer), mirroring Python's FastAPI
        // add_security_headers middleware — NOT baked into this primitive.
        $svc = $this->makeService();

        [$status, $headers,] = $svc->handleRequest('GET', '/', $this->authHeader());
        $this->assertSame(200, $status);
        $this->assertSame([], $headers, '200 SWML core response must carry no headers');

        [$status401, $headers401,] = $svc->handleRequest('GET', '/');
        $this->assertSame(401, $status401);
        $this->assertSame(['WWW-Authenticate'], array_keys($headers401));
        $this->assertSame('Basic', $headers401['WWW-Authenticate']);
    }

    // ------------------------------------------------------------------
    // HTTP Handling: SWML / SWAIG / PostPrompt
    // ------------------------------------------------------------------

    public function testSwmlEndpointReturnsDocument(): void
    {
        $svc = $this->makeService();
        $svc->answer(['max_duration' => 3600])->hangup(); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)

        [$status, , $body] = $svc->handleRequest('GET', '/', $this->authHeader());
        $this->assertSame(200, $status);

        $decoded = json_decode($body, true);
        $this->assertSame('1.0.0', Shape::at($decoded, 'version'));
        $this->assertCount(2, Shape::sub($decoded, 'sections', 'main'));
    }

    public function testSwaigEndpointAuth(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('POST', '/swaig');
        $this->assertSame(401, $status);
    }

    public function testSwaigEndpointWithAuth(): void
    {
        // After the SWAIG lift, the endpoint validates the body. An empty
        // body with no `function` name now returns 400. The test exists to
        // prove the route is mounted under auth — 400 is the correct lifted
        // behavior; the stub-200 the old test asserted was a no-op handler.
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('POST', '/swaig', $this->authHeader(), '{}');
        $this->assertSame(400, $status);
    }

    public function testPostPromptEndpointAuth(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('POST', '/post_prompt');
        $this->assertSame(401, $status);
    }

    public function testPostPromptEndpointWithAuth(): void
    {
        $svc = $this->makeService();
        [$status,,] = $svc->handleRequest('POST', '/post_prompt', $this->authHeader(), '{}');
        $this->assertSame(200, $status);
    }

    // ------------------------------------------------------------------
    // HTTP Handling: Custom Route
    // ------------------------------------------------------------------

    public function testCustomRouteSwml(): void
    {
        $svc = $this->makeService(['route' => '/agent']);
        $svc->hangup(); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)

        [$status, , $body] = $svc->handleRequest('GET', '/agent', $this->authHeader());
        $this->assertSame(200, $status);

        $decoded = json_decode($body, true);
        $this->assertCount(1, Shape::sub($decoded, 'sections', 'main'));
    }

    public function testCustomRouteSwaig(): void
    {
        // Lifted handler validates body — empty body returns 400 (missing
        // function name). The point of the test is that /agent/swaig routes
        // through the route prefix to handleSwaigRequest, which it does.
        $svc = $this->makeService(['route' => '/agent']);
        [$status,,] = $svc->handleRequest('POST', '/agent/swaig', $this->authHeader(), '{}');
        $this->assertSame(400, $status);
    }

    public function testCustomRoutePostPrompt(): void
    {
        $svc = $this->makeService(['route' => '/agent']);
        [$status,,] = $svc->handleRequest('POST', '/agent/post_prompt', $this->authHeader(), '{}');
        $this->assertSame(200, $status);
    }

    public function testCustomRouteHealthStillWorks(): void
    {
        $svc = $this->makeService(['route' => '/agent']);
        [$status,,] = $svc->handleRequest('GET', '/health');
        $this->assertSame(200, $status);
    }

    public function testUnmatchedRouteReturns404(): void
    {
        $svc = $this->makeService(['route' => '/agent']);
        [$status,,] = $svc->handleRequest('GET', '/other', $this->authHeader());
        $this->assertSame(404, $status);
    }

    // ------------------------------------------------------------------
    // HTTP Handling: Body size limit
    // ------------------------------------------------------------------

    public function testBodySizeLimit(): void
    {
        $svc = $this->makeService();
        $hugeBody = str_repeat('x', 1_048_577); // 1MB + 1 byte
        [$status,,] = $svc->handleRequest('POST', '/', $this->authHeader(), $hugeBody);
        $this->assertSame(413, $status);
    }

    // ------------------------------------------------------------------
    // Routing Callbacks
    // ------------------------------------------------------------------

    public function testRoutingCallbackRedirectReturnsRoute(): void
    {
        // Python contract (agent_base.py:1757): the routing callback is
        // (body, headers) -> route|null. A route string yields a 307 redirect
        // preserving method+body, with the returned route as the Location.
        $svc = $this->makeService();
        $called = false;
        $svc->registerRoutingCallback('/custom', function (?array $data, array $headers) use (&$called) {
            $called = true;
            return '/other-service';
        });

        [$status, $headers, $body] = $svc->handleRequest('POST', '/custom', $this->authHeader(), '{}');
        $this->assertTrue($called);
        $this->assertSame(307, $status);
        $this->assertSame('/other-service', $headers['Location'] ?? null);
        $this->assertSame('', $body);
    }

    public function testRoutingCallbackNullContinuesToSwml(): void
    {
        // When the callback declines (returns null), the request is served by
        // this service — it renders and returns the SWML document (200).
        $svc = $this->makeService();
        $called = false;
        $svc->registerRoutingCallback('/custom', function (?array $data, array $headers) use (&$called) {
            $called = true;
            return null;
        });

        [$status, , $body] = $svc->handleRequest('POST', '/custom', $this->authHeader(), '{}');
        $this->assertTrue($called);
        $this->assertSame(200, $status);
        $decoded = json_decode($body, true);
        $this->assertIsArray($decoded);
        $this->assertSame('1.0.0', Shape::at($decoded, 'version'));
    }

    // ------------------------------------------------------------------
    // SIP Username Extraction
    // ------------------------------------------------------------------

    public function testExtractSipUsername(): void
    {
        $body = ['call' => ['to' => 'sip:agent1@example.com']];
        $this->assertSame('agent1', Service::extractSipUsername($body));
    }

    public function testExtractSipUsernameTel(): void
    {
        // Python parity: a tel: URI returns the phone number after "tel:".
        $body = ['call' => ['to' => 'tel:+15551234567']];
        $this->assertSame('+15551234567', Service::extractSipUsername($body));
    }

    public function testExtractSipUsernamePlain(): void
    {
        // Neither sip: nor tel: -> the whole call.to field, verbatim.
        $body = ['call' => ['to' => 'support']];
        $this->assertSame('support', Service::extractSipUsername($body));
    }

    public function testExtractSipUsernameNull(): void
    {
        // Only call.to is consulted (Python parity: no top-level `to` fallback).
        $this->assertNull(Service::extractSipUsername(null));
        $this->assertNull(Service::extractSipUsername([]));
        $this->assertNull(Service::extractSipUsername(['to' => 'sip:x@host.com']));
    }

    public function testExtractSipUsernameReturnsRawValue(): void
    {
        // Python parity: the extractor performs NO character/length validation —
        // it returns the raw username between "sip:" and "@" as-is.
        $body = ['call' => ['to' => 'sip:user.name-test_1@host.com']];
        $this->assertSame('user.name-test_1', Service::extractSipUsername($body));
    }

    // ------------------------------------------------------------------
    // Proxy URL Base
    // ------------------------------------------------------------------

    public function testProxyUrlFromEnv(): void
    {
        putenv('SWML_PROXY_URL_BASE=https://proxy.example.com');
        $svc = $this->makeService();
        $this->assertSame('https://proxy.example.com', $svc->getProxyUrlBase());
    }

    public function testProxyUrlFromForwardedHeaders(): void
    {
        $svc = $this->makeService();
        $headers = [
            'X-Forwarded-Proto' => 'https',
            'X-Forwarded-Host' => 'myapp.example.com',
        ];
        $this->assertSame('https://myapp.example.com', $svc->getProxyUrlBase($headers));
    }

    public function testProxyUrlFromOriginalUrl(): void
    {
        $svc = $this->makeService();
        $headers = ['X-Original-URL' => 'https://original.example.com/path'];
        $this->assertSame('https://original.example.com/path', $svc->getProxyUrlBase($headers));
    }

    public function testProxyUrlFallback(): void
    {
        $svc = $this->makeService(['host' => '0.0.0.0', 'port' => 3000]);
        $this->assertSame('http://0.0.0.0:3000', $svc->getProxyUrlBase());
    }

    // ------------------------------------------------------------------
    // Render
    // ------------------------------------------------------------------

    public function testRender(): void
    {
        $svc = $this->makeService();
        $svc->hangup(); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)
        $json = $svc->render();
        $decoded = json_decode($json, true);
        $this->assertSame('1.0.0', Shape::at($decoded, 'version'));
    }

    public function testRenderPretty(): void
    {
        $svc = $this->makeService();
        $svc->hangup(); // @phpstan-ignore method.notFound (auto-vivified SWML verb via __call)
        $json = $svc->renderPretty();
        $this->assertStringContainsString("\n", $json);
    }
}
